# Generated by Django 6.0.2 on 2026-04-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_name_order_total_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='stripe', max_length=50),
        ),
    ]
